//! Suppliers store

use components::prelude::*;
use super::types::{
    Supplier, SupplierFilter, SupplierStatus, SupplierKpis, PaginationState,
    BbbeeLevel, RiskRating, PerformanceScore, PerformanceTrend,
    SupplierCategory, RiskIndicator, RiskIndicatorStatus, SupplierContract,
};

/// Suppliers state store
#[derive(Clone)]
pub struct SuppliersStore {
    pub suppliers: Signal<Vec<Supplier>>,
    pub selected: Signal<Option<Supplier>>,
    pub filter: Signal<SupplierFilter>,
    pub pagination: Signal<PaginationState>,
    pub kpis: Signal<SupplierKpis>,
    pub loading: Signal<bool>,
    pub error: Signal<Option<String>>,
}

impl SuppliersStore {
    pub fn new() -> Self {
        Self {
            suppliers: signal(Vec::new()),
            selected: signal(None),
            filter: signal(SupplierFilter::default()),
            pagination: signal(PaginationState::default()),
            kpis: signal(SupplierKpis::default()),
            loading: signal(false),
            error: signal(None),
        }
    }
}

/// Load mock South African supplier data for demo
pub fn load_mock_data(store: &SuppliersStore) {
    let mock_suppliers = vec![
        Supplier {
            id: "SUP-001".to_string(),
            name: "TechSolutions SA (Pty) Ltd".to_string(),
            trading_name: Some("TechSolutions".to_string()),
            registration_number: "2015/123456/07".to_string(),
            tax_number: Some("9012345678".to_string()),
            vat_number: Some("4012345678".to_string()),
            bbbee_level: BbbeeLevel::Level1,
            bbbee_certificate_number: Some("BEE-2024-78901".to_string()),
            bbbee_expiry_date: Some("2025-12-31".to_string()),
            bbbee_verification_agency: Some("Empowerdex".to_string()),
            categories: vec![
                SupplierCategory {
                    code: "IT-001".to_string(),
                    name: "Information Technology".to_string(),
                    description: "IT hardware, software and services".to_string(),
                },
                SupplierCategory {
                    code: "IT-003".to_string(),
                    name: "Cloud Services".to_string(),
                    description: "Cloud computing and hosting services".to_string(),
                },
            ],
            performance_score: PerformanceScore {
                overall: 92.5,
                quality: 95.0,
                delivery: 90.0,
                price: 88.0,
                responsiveness: 94.0,
                compliance: 96.0,
            },
            performance_history: vec![
                PerformanceTrend { period: "2024-Q1".to_string(), score: 88.0 },
                PerformanceTrend { period: "2024-Q2".to_string(), score: 90.0 },
                PerformanceTrend { period: "2024-Q3".to_string(), score: 91.5 },
                PerformanceTrend { period: "2024-Q4".to_string(), score: 92.5 },
            ],
            risk_rating: RiskRating::Low,
            risk_indicators: vec![],
            risk_score: 15.0,
            contact_person: "Thabo Molefe".to_string(),
            email: "thabo.molefe@techsolutions.co.za".to_string(),
            phone: "+27 11 234 5678".to_string(),
            physical_address: "123 Innovation Drive, Sandton, 2196".to_string(),
            postal_address: Some("PO Box 12345, Sandton, 2196".to_string()),
            province: "Gauteng".to_string(),
            city: "Johannesburg".to_string(),
            bank_name: Some("First National Bank".to_string()),
            bank_account_number: Some("****5678".to_string()),
            bank_branch_code: Some("250655".to_string()),
            status: SupplierStatus::Active,
            registered_at: "2019-03-15".to_string(),
            verified_at: Some("2019-03-20".to_string()),
            last_active: "2025-02-10".to_string(),
            active_contracts: 3,
            total_contract_value: 45_000_000.0,
            contracts: vec![
                SupplierContract {
                    id: "CTR-2024-001".to_string(),
                    reference: "IT Infrastructure Support".to_string(),
                    description: "Annual IT support and maintenance".to_string(),
                    value: 12_000_000.0,
                    start_date: "2024-04-01".to_string(),
                    end_date: "2027-03-31".to_string(),
                    status: "Active".to_string(),
                },
            ],
            csd_number: Some("MAAA0012345".to_string()),
            csd_verified: true,
        },
        Supplier {
            id: "SUP-002".to_string(),
            name: "Ubuntu Construction Group".to_string(),
            trading_name: Some("Ubuntu Build".to_string()),
            registration_number: "2012/789012/07".to_string(),
            tax_number: Some("9087654321".to_string()),
            vat_number: Some("4087654321".to_string()),
            bbbee_level: BbbeeLevel::Level2,
            bbbee_certificate_number: Some("BEE-2024-45678".to_string()),
            bbbee_expiry_date: Some("2025-09-30".to_string()),
            bbbee_verification_agency: Some("SANAS".to_string()),
            categories: vec![
                SupplierCategory {
                    code: "CON-001".to_string(),
                    name: "Construction".to_string(),
                    description: "Building and construction services".to_string(),
                },
                SupplierCategory {
                    code: "CON-002".to_string(),
                    name: "Civil Engineering".to_string(),
                    description: "Civil engineering projects".to_string(),
                },
            ],
            performance_score: PerformanceScore {
                overall: 85.0,
                quality: 88.0,
                delivery: 78.0,
                price: 85.0,
                responsiveness: 82.0,
                compliance: 92.0,
            },
            performance_history: vec![
                PerformanceTrend { period: "2024-Q1".to_string(), score: 82.0 },
                PerformanceTrend { period: "2024-Q2".to_string(), score: 83.5 },
                PerformanceTrend { period: "2024-Q3".to_string(), score: 84.0 },
                PerformanceTrend { period: "2024-Q4".to_string(), score: 85.0 },
            ],
            risk_rating: RiskRating::Medium,
            risk_indicators: vec![
                RiskIndicator {
                    id: "RISK-001".to_string(),
                    category: "Financial".to_string(),
                    indicator: "High debt-to-equity ratio".to_string(),
                    severity: RiskRating::Medium,
                    description: "Current debt levels require monitoring".to_string(),
                    detected_at: "2024-11-15".to_string(),
                    status: RiskIndicatorStatus::UnderReview,
                },
            ],
            risk_score: 45.0,
            contact_person: "Nomvula Dlamini".to_string(),
            email: "nomvula@ubuntuconstruction.co.za".to_string(),
            phone: "+27 12 345 6789".to_string(),
            physical_address: "456 Builder Street, Centurion, 0157".to_string(),
            postal_address: None,
            province: "Gauteng".to_string(),
            city: "Pretoria".to_string(),
            bank_name: Some("Standard Bank".to_string()),
            bank_account_number: Some("****9012".to_string()),
            bank_branch_code: Some("051001".to_string()),
            status: SupplierStatus::Active,
            registered_at: "2018-06-20".to_string(),
            verified_at: Some("2018-07-01".to_string()),
            last_active: "2025-02-08".to_string(),
            active_contracts: 2,
            total_contract_value: 28_500_000.0,
            contracts: vec![],
            csd_number: Some("MAAA0067890".to_string()),
            csd_verified: true,
        },
        Supplier {
            id: "SUP-003".to_string(),
            name: "Cape Catering Services CC".to_string(),
            trading_name: Some("Cape Caterers".to_string()),
            registration_number: "CK2010/045678".to_string(),
            tax_number: Some("9023456789".to_string()),
            vat_number: Some("4023456789".to_string()),
            bbbee_level: BbbeeLevel::Level1,
            bbbee_certificate_number: Some("BEE-2024-23456".to_string()),
            bbbee_expiry_date: Some("2025-06-30".to_string()),
            bbbee_verification_agency: Some("Empowerdex".to_string()),
            categories: vec![
                SupplierCategory {
                    code: "CAT-001".to_string(),
                    name: "Catering Services".to_string(),
                    description: "Food and catering services".to_string(),
                },
            ],
            performance_score: PerformanceScore {
                overall: 94.0,
                quality: 96.0,
                delivery: 95.0,
                price: 90.0,
                responsiveness: 93.0,
                compliance: 96.0,
            },
            performance_history: vec![
                PerformanceTrend { period: "2024-Q1".to_string(), score: 91.0 },
                PerformanceTrend { period: "2024-Q2".to_string(), score: 92.0 },
                PerformanceTrend { period: "2024-Q3".to_string(), score: 93.0 },
                PerformanceTrend { period: "2024-Q4".to_string(), score: 94.0 },
            ],
            risk_rating: RiskRating::Low,
            risk_indicators: vec![],
            risk_score: 10.0,
            contact_person: "Fatima Adams".to_string(),
            email: "fatima@capecaterers.co.za".to_string(),
            phone: "+27 21 456 7890".to_string(),
            physical_address: "789 Food Court, Cape Town CBD, 8001".to_string(),
            postal_address: Some("PO Box 789, Cape Town, 8000".to_string()),
            province: "Western Cape".to_string(),
            city: "Cape Town".to_string(),
            bank_name: Some("ABSA".to_string()),
            bank_account_number: Some("****3456".to_string()),
            bank_branch_code: Some("632005".to_string()),
            status: SupplierStatus::Active,
            registered_at: "2017-01-10".to_string(),
            verified_at: Some("2017-01-15".to_string()),
            last_active: "2025-02-12".to_string(),
            active_contracts: 4,
            total_contract_value: 8_200_000.0,
            contracts: vec![],
            csd_number: Some("MAAA0034567".to_string()),
            csd_verified: true,
        },
        Supplier {
            id: "SUP-004".to_string(),
            name: "SecureGuard Holdings (Pty) Ltd".to_string(),
            trading_name: Some("SecureGuard".to_string()),
            registration_number: "2008/567890/07".to_string(),
            tax_number: Some("9034567890".to_string()),
            vat_number: Some("4034567890".to_string()),
            bbbee_level: BbbeeLevel::Level1,
            bbbee_certificate_number: Some("BEE-2024-34567".to_string()),
            bbbee_expiry_date: Some("2025-11-30".to_string()),
            bbbee_verification_agency: Some("BEE Verification Agency".to_string()),
            categories: vec![
                SupplierCategory {
                    code: "SEC-001".to_string(),
                    name: "Security Services".to_string(),
                    description: "Physical security and guarding".to_string(),
                },
                SupplierCategory {
                    code: "SEC-002".to_string(),
                    name: "Armed Response".to_string(),
                    description: "Armed response services".to_string(),
                },
            ],
            performance_score: PerformanceScore {
                overall: 88.5,
                quality: 90.0,
                delivery: 92.0,
                price: 82.0,
                responsiveness: 88.0,
                compliance: 91.0,
            },
            performance_history: vec![
                PerformanceTrend { period: "2024-Q1".to_string(), score: 86.0 },
                PerformanceTrend { period: "2024-Q2".to_string(), score: 87.0 },
                PerformanceTrend { period: "2024-Q3".to_string(), score: 88.0 },
                PerformanceTrend { period: "2024-Q4".to_string(), score: 88.5 },
            ],
            risk_rating: RiskRating::Low,
            risk_indicators: vec![],
            risk_score: 20.0,
            contact_person: "Sipho Mkhize".to_string(),
            email: "sipho.mkhize@secureguard.co.za".to_string(),
            phone: "+27 31 567 8901".to_string(),
            physical_address: "321 Security Lane, Durban North, 4051".to_string(),
            postal_address: None,
            province: "KwaZulu-Natal".to_string(),
            city: "Durban".to_string(),
            bank_name: Some("Nedbank".to_string()),
            bank_account_number: Some("****7890".to_string()),
            bank_branch_code: Some("198765".to_string()),
            status: SupplierStatus::Active,
            registered_at: "2016-09-01".to_string(),
            verified_at: Some("2016-09-10".to_string()),
            last_active: "2025-02-11".to_string(),
            active_contracts: 5,
            total_contract_value: 35_000_000.0,
            contracts: vec![],
            csd_number: Some("MAAA0089012".to_string()),
            csd_verified: true,
        },
        Supplier {
            id: "SUP-005".to_string(),
            name: "GreenTech Environmental Solutions".to_string(),
            trading_name: Some("GreenTech".to_string()),
            registration_number: "2019/234567/07".to_string(),
            tax_number: Some("9045678901".to_string()),
            vat_number: Some("4045678901".to_string()),
            bbbee_level: BbbeeLevel::Level1,
            bbbee_certificate_number: Some("BEE-2025-12345".to_string()),
            bbbee_expiry_date: Some("2026-03-31".to_string()),
            bbbee_verification_agency: Some("AQRate".to_string()),
            categories: vec![
                SupplierCategory {
                    code: "ENV-001".to_string(),
                    name: "Environmental Services".to_string(),
                    description: "Environmental consulting and remediation".to_string(),
                },
                SupplierCategory {
                    code: "ENV-002".to_string(),
                    name: "Waste Management".to_string(),
                    description: "Waste collection and recycling".to_string(),
                },
            ],
            performance_score: PerformanceScore {
                overall: 91.0,
                quality: 93.0,
                delivery: 89.0,
                price: 88.0,
                responsiveness: 92.0,
                compliance: 94.0,
            },
            performance_history: vec![
                PerformanceTrend { period: "2024-Q1".to_string(), score: 87.0 },
                PerformanceTrend { period: "2024-Q2".to_string(), score: 89.0 },
                PerformanceTrend { period: "2024-Q3".to_string(), score: 90.0 },
                PerformanceTrend { period: "2024-Q4".to_string(), score: 91.0 },
            ],
            risk_rating: RiskRating::Low,
            risk_indicators: vec![],
            risk_score: 12.0,
            contact_person: "Lerato Mokoena".to_string(),
            email: "lerato@greentech-sa.co.za".to_string(),
            phone: "+27 11 678 9012".to_string(),
            physical_address: "567 Eco Park, Midrand, 1685".to_string(),
            postal_address: Some("Private Bag X100, Midrand, 1685".to_string()),
            province: "Gauteng".to_string(),
            city: "Johannesburg".to_string(),
            bank_name: Some("Investec".to_string()),
            bank_account_number: Some("****2345".to_string()),
            bank_branch_code: Some("580105".to_string()),
            status: SupplierStatus::Active,
            registered_at: "2020-02-14".to_string(),
            verified_at: Some("2020-02-20".to_string()),
            last_active: "2025-02-09".to_string(),
            active_contracts: 2,
            total_contract_value: 15_500_000.0,
            contracts: vec![],
            csd_number: Some("MAAA0056789".to_string()),
            csd_verified: true,
        },
        Supplier {
            id: "SUP-006".to_string(),
            name: "Protea Professional Services".to_string(),
            trading_name: None,
            registration_number: "2014/890123/07".to_string(),
            tax_number: Some("9056789012".to_string()),
            vat_number: Some("4056789012".to_string()),
            bbbee_level: BbbeeLevel::Level3,
            bbbee_certificate_number: Some("BEE-2024-56789".to_string()),
            bbbee_expiry_date: Some("2025-04-30".to_string()),
            bbbee_verification_agency: Some("SANAS".to_string()),
            categories: vec![
                SupplierCategory {
                    code: "PRO-001".to_string(),
                    name: "Professional Services".to_string(),
                    description: "Consulting and advisory services".to_string(),
                },
                SupplierCategory {
                    code: "PRO-002".to_string(),
                    name: "Audit Services".to_string(),
                    description: "Internal and external audit".to_string(),
                },
            ],
            performance_score: PerformanceScore {
                overall: 78.0,
                quality: 82.0,
                delivery: 72.0,
                price: 80.0,
                responsiveness: 75.0,
                compliance: 81.0,
            },
            performance_history: vec![
                PerformanceTrend { period: "2024-Q1".to_string(), score: 80.0 },
                PerformanceTrend { period: "2024-Q2".to_string(), score: 79.0 },
                PerformanceTrend { period: "2024-Q3".to_string(), score: 77.0 },
                PerformanceTrend { period: "2024-Q4".to_string(), score: 78.0 },
            ],
            risk_rating: RiskRating::Medium,
            risk_indicators: vec![
                RiskIndicator {
                    id: "RISK-002".to_string(),
                    category: "Performance".to_string(),
                    indicator: "Declining performance trend".to_string(),
                    severity: RiskRating::Medium,
                    description: "Performance scores have declined over 3 quarters".to_string(),
                    detected_at: "2024-12-01".to_string(),
                    status: RiskIndicatorStatus::Open,
                },
            ],
            risk_score: 42.0,
            contact_person: "James van der Berg".to_string(),
            email: "james@proteapro.co.za".to_string(),
            phone: "+27 21 789 0123".to_string(),
            physical_address: "890 Professional Tower, Bellville, 7530".to_string(),
            postal_address: None,
            province: "Western Cape".to_string(),
            city: "Cape Town".to_string(),
            bank_name: Some("Standard Bank".to_string()),
            bank_account_number: Some("****6789".to_string()),
            bank_branch_code: Some("051001".to_string()),
            status: SupplierStatus::Active,
            registered_at: "2018-11-05".to_string(),
            verified_at: Some("2018-11-12".to_string()),
            last_active: "2025-01-28".to_string(),
            active_contracts: 1,
            total_contract_value: 4_500_000.0,
            contracts: vec![],
            csd_number: Some("MAAA0023456".to_string()),
            csd_verified: true,
        },
        Supplier {
            id: "SUP-007".to_string(),
            name: "Mpumalanga Transport Logistics".to_string(),
            trading_name: Some("MTL Logistics".to_string()),
            registration_number: "2016/345678/07".to_string(),
            tax_number: Some("9067890123".to_string()),
            vat_number: Some("4067890123".to_string()),
            bbbee_level: BbbeeLevel::Level2,
            bbbee_certificate_number: Some("BEE-2024-67890".to_string()),
            bbbee_expiry_date: Some("2025-08-31".to_string()),
            bbbee_verification_agency: Some("Empowerdex".to_string()),
            categories: vec![
                SupplierCategory {
                    code: "TRN-001".to_string(),
                    name: "Transport Services".to_string(),
                    description: "Road transport and logistics".to_string(),
                },
                SupplierCategory {
                    code: "TRN-002".to_string(),
                    name: "Fleet Management".to_string(),
                    description: "Vehicle fleet management services".to_string(),
                },
            ],
            performance_score: PerformanceScore {
                overall: 86.5,
                quality: 85.0,
                delivery: 88.0,
                price: 87.0,
                responsiveness: 84.0,
                compliance: 89.0,
            },
            performance_history: vec![
                PerformanceTrend { period: "2024-Q1".to_string(), score: 84.0 },
                PerformanceTrend { period: "2024-Q2".to_string(), score: 85.0 },
                PerformanceTrend { period: "2024-Q3".to_string(), score: 86.0 },
                PerformanceTrend { period: "2024-Q4".to_string(), score: 86.5 },
            ],
            risk_rating: RiskRating::Low,
            risk_indicators: vec![],
            risk_score: 18.0,
            contact_person: "Peter Nkosi".to_string(),
            email: "peter@mtllogistics.co.za".to_string(),
            phone: "+27 13 234 5678".to_string(),
            physical_address: "234 Industrial Road, Nelspruit, 1200".to_string(),
            postal_address: None,
            province: "Mpumalanga".to_string(),
            city: "Mbombela".to_string(),
            bank_name: Some("First National Bank".to_string()),
            bank_account_number: Some("****0123".to_string()),
            bank_branch_code: Some("250655".to_string()),
            status: SupplierStatus::Active,
            registered_at: "2019-07-22".to_string(),
            verified_at: Some("2019-07-30".to_string()),
            last_active: "2025-02-07".to_string(),
            active_contracts: 3,
            total_contract_value: 18_000_000.0,
            contracts: vec![],
            csd_number: Some("MAAA0045678".to_string()),
            csd_verified: true,
        },
        Supplier {
            id: "SUP-008".to_string(),
            name: "Eastern Cape Medical Supplies".to_string(),
            trading_name: Some("EC Medicals".to_string()),
            registration_number: "2011/456789/07".to_string(),
            tax_number: Some("9078901234".to_string()),
            vat_number: Some("4078901234".to_string()),
            bbbee_level: BbbeeLevel::Level4,
            bbbee_certificate_number: Some("BEE-2024-78901".to_string()),
            bbbee_expiry_date: Some("2025-03-31".to_string()),
            bbbee_verification_agency: Some("SANAS".to_string()),
            categories: vec![
                SupplierCategory {
                    code: "MED-001".to_string(),
                    name: "Medical Supplies".to_string(),
                    description: "Medical equipment and consumables".to_string(),
                },
            ],
            performance_score: PerformanceScore {
                overall: 72.0,
                quality: 78.0,
                delivery: 65.0,
                price: 75.0,
                responsiveness: 70.0,
                compliance: 72.0,
            },
            performance_history: vec![
                PerformanceTrend { period: "2024-Q1".to_string(), score: 75.0 },
                PerformanceTrend { period: "2024-Q2".to_string(), score: 74.0 },
                PerformanceTrend { period: "2024-Q3".to_string(), score: 73.0 },
                PerformanceTrend { period: "2024-Q4".to_string(), score: 72.0 },
            ],
            risk_rating: RiskRating::High,
            risk_indicators: vec![
                RiskIndicator {
                    id: "RISK-003".to_string(),
                    category: "Delivery".to_string(),
                    indicator: "Consistent late deliveries".to_string(),
                    severity: RiskRating::High,
                    description: "Multiple instances of delivery delays exceeding 7 days".to_string(),
                    detected_at: "2024-10-15".to_string(),
                    status: RiskIndicatorStatus::Open,
                },
                RiskIndicator {
                    id: "RISK-004".to_string(),
                    category: "Compliance".to_string(),
                    indicator: "B-BBEE certificate expiring soon".to_string(),
                    severity: RiskRating::Medium,
                    description: "Certificate expires in less than 60 days".to_string(),
                    detected_at: "2025-02-01".to_string(),
                    status: RiskIndicatorStatus::Open,
                },
            ],
            risk_score: 68.0,
            contact_person: "Andile Mgweba".to_string(),
            email: "andile@ecmedicals.co.za".to_string(),
            phone: "+27 41 345 6789".to_string(),
            physical_address: "567 Health Street, Port Elizabeth, 6001".to_string(),
            postal_address: Some("PO Box 567, Port Elizabeth, 6000".to_string()),
            province: "Eastern Cape".to_string(),
            city: "Gqeberha".to_string(),
            bank_name: Some("ABSA".to_string()),
            bank_account_number: Some("****4567".to_string()),
            bank_branch_code: Some("632005".to_string()),
            status: SupplierStatus::Active,
            registered_at: "2017-04-18".to_string(),
            verified_at: Some("2017-04-25".to_string()),
            last_active: "2025-01-20".to_string(),
            active_contracts: 1,
            total_contract_value: 6_800_000.0,
            contracts: vec![],
            csd_number: Some("MAAA0078901".to_string()),
            csd_verified: true,
        },
        Supplier {
            id: "SUP-009".to_string(),
            name: "Limpopo Cleaning Services".to_string(),
            trading_name: None,
            registration_number: "2020/567890/07".to_string(),
            tax_number: Some("9089012345".to_string()),
            vat_number: None,
            bbbee_level: BbbeeLevel::Level1,
            bbbee_certificate_number: Some("BEE-2024-89012".to_string()),
            bbbee_expiry_date: Some("2025-10-31".to_string()),
            bbbee_verification_agency: Some("AQRate".to_string()),
            categories: vec![
                SupplierCategory {
                    code: "CLN-001".to_string(),
                    name: "Cleaning Services".to_string(),
                    description: "Commercial and industrial cleaning".to_string(),
                },
            ],
            performance_score: PerformanceScore {
                overall: 89.0,
                quality: 91.0,
                delivery: 90.0,
                price: 88.0,
                responsiveness: 87.0,
                compliance: 89.0,
            },
            performance_history: vec![
                PerformanceTrend { period: "2024-Q1".to_string(), score: 85.0 },
                PerformanceTrend { period: "2024-Q2".to_string(), score: 87.0 },
                PerformanceTrend { period: "2024-Q3".to_string(), score: 88.0 },
                PerformanceTrend { period: "2024-Q4".to_string(), score: 89.0 },
            ],
            risk_rating: RiskRating::Low,
            risk_indicators: vec![],
            risk_score: 14.0,
            contact_person: "Maria Maluleke".to_string(),
            email: "maria@limpopoclean.co.za".to_string(),
            phone: "+27 15 456 7890".to_string(),
            physical_address: "123 Clean Street, Polokwane, 0700".to_string(),
            postal_address: None,
            province: "Limpopo".to_string(),
            city: "Polokwane".to_string(),
            bank_name: Some("Capitec".to_string()),
            bank_account_number: Some("****8901".to_string()),
            bank_branch_code: Some("470010".to_string()),
            status: SupplierStatus::Active,
            registered_at: "2021-08-30".to_string(),
            verified_at: Some("2021-09-05".to_string()),
            last_active: "2025-02-10".to_string(),
            active_contracts: 2,
            total_contract_value: 3_200_000.0,
            contracts: vec![],
            csd_number: Some("MAAA0090123".to_string()),
            csd_verified: true,
        },
        Supplier {
            id: "SUP-010".to_string(),
            name: "Free State Furniture Factory".to_string(),
            trading_name: Some("FS Furniture".to_string()),
            registration_number: "2013/678901/07".to_string(),
            tax_number: Some("9090123456".to_string()),
            vat_number: Some("4090123456".to_string()),
            bbbee_level: BbbeeLevel::Level2,
            bbbee_certificate_number: Some("BEE-2024-90123".to_string()),
            bbbee_expiry_date: Some("2025-07-31".to_string()),
            bbbee_verification_agency: Some("Empowerdex".to_string()),
            categories: vec![
                SupplierCategory {
                    code: "FUR-001".to_string(),
                    name: "Office Furniture".to_string(),
                    description: "Office furniture and fittings".to_string(),
                },
            ],
            performance_score: PerformanceScore {
                overall: 83.0,
                quality: 86.0,
                delivery: 80.0,
                price: 84.0,
                responsiveness: 81.0,
                compliance: 84.0,
            },
            performance_history: vec![
                PerformanceTrend { period: "2024-Q1".to_string(), score: 81.0 },
                PerformanceTrend { period: "2024-Q2".to_string(), score: 82.0 },
                PerformanceTrend { period: "2024-Q3".to_string(), score: 82.5 },
                PerformanceTrend { period: "2024-Q4".to_string(), score: 83.0 },
            ],
            risk_rating: RiskRating::Low,
            risk_indicators: vec![],
            risk_score: 22.0,
            contact_person: "Johan Pretorius".to_string(),
            email: "johan@fsfurniture.co.za".to_string(),
            phone: "+27 51 567 8901".to_string(),
            physical_address: "456 Factory Road, Bloemfontein, 9301".to_string(),
            postal_address: Some("PO Box 456, Bloemfontein, 9300".to_string()),
            province: "Free State".to_string(),
            city: "Bloemfontein".to_string(),
            bank_name: Some("Standard Bank".to_string()),
            bank_account_number: Some("****2345".to_string()),
            bank_branch_code: Some("051001".to_string()),
            status: SupplierStatus::Active,
            registered_at: "2018-03-12".to_string(),
            verified_at: Some("2018-03-20".to_string()),
            last_active: "2025-02-05".to_string(),
            active_contracts: 1,
            total_contract_value: 2_100_000.0,
            contracts: vec![],
            csd_number: Some("MAAA0012346".to_string()),
            csd_verified: true,
        },
        Supplier {
            id: "SUP-011".to_string(),
            name: "Risky Ventures Trading".to_string(),
            trading_name: None,
            registration_number: "2017/789012/07".to_string(),
            tax_number: Some("9012345679".to_string()),
            vat_number: None,
            bbbee_level: BbbeeLevel::NonCompliant,
            bbbee_certificate_number: None,
            bbbee_expiry_date: None,
            bbbee_verification_agency: None,
            categories: vec![
                SupplierCategory {
                    code: "GEN-001".to_string(),
                    name: "General Supplies".to_string(),
                    description: "General office and consumable supplies".to_string(),
                },
            ],
            performance_score: PerformanceScore {
                overall: 58.0,
                quality: 55.0,
                delivery: 50.0,
                price: 70.0,
                responsiveness: 52.0,
                compliance: 63.0,
            },
            performance_history: vec![
                PerformanceTrend { period: "2024-Q1".to_string(), score: 65.0 },
                PerformanceTrend { period: "2024-Q2".to_string(), score: 62.0 },
                PerformanceTrend { period: "2024-Q3".to_string(), score: 60.0 },
                PerformanceTrend { period: "2024-Q4".to_string(), score: 58.0 },
            ],
            risk_rating: RiskRating::Critical,
            risk_indicators: vec![
                RiskIndicator {
                    id: "RISK-005".to_string(),
                    category: "Compliance".to_string(),
                    indicator: "No B-BBEE certificate".to_string(),
                    severity: RiskRating::High,
                    description: "Supplier has no valid B-BBEE certification".to_string(),
                    detected_at: "2024-06-01".to_string(),
                    status: RiskIndicatorStatus::Open,
                },
                RiskIndicator {
                    id: "RISK-006".to_string(),
                    category: "Financial".to_string(),
                    indicator: "Payment disputes".to_string(),
                    severity: RiskRating::High,
                    description: "Multiple unresolved payment disputes with sub-contractors".to_string(),
                    detected_at: "2024-09-15".to_string(),
                    status: RiskIndicatorStatus::UnderReview,
                },
                RiskIndicator {
                    id: "RISK-007".to_string(),
                    category: "Performance".to_string(),
                    indicator: "Critical performance decline".to_string(),
                    severity: RiskRating::Critical,
                    description: "Performance has declined below acceptable threshold of 60%".to_string(),
                    detected_at: "2024-12-15".to_string(),
                    status: RiskIndicatorStatus::Open,
                },
            ],
            risk_score: 85.0,
            contact_person: "Unknown Contact".to_string(),
            email: "info@riskyventures.co.za".to_string(),
            phone: "+27 11 000 0000".to_string(),
            physical_address: "Unknown Address, Johannesburg".to_string(),
            postal_address: None,
            province: "Gauteng".to_string(),
            city: "Johannesburg".to_string(),
            bank_name: None,
            bank_account_number: None,
            bank_branch_code: None,
            status: SupplierStatus::Suspended,
            registered_at: "2019-05-01".to_string(),
            verified_at: None,
            last_active: "2024-10-15".to_string(),
            active_contracts: 0,
            total_contract_value: 500_000.0,
            contracts: vec![],
            csd_number: None,
            csd_verified: false,
        },
        Supplier {
            id: "SUP-012".to_string(),
            name: "North West Mining Equipment".to_string(),
            trading_name: Some("NW Mining".to_string()),
            registration_number: "2009/012345/07".to_string(),
            tax_number: Some("9023456780".to_string()),
            vat_number: Some("4023456780".to_string()),
            bbbee_level: BbbeeLevel::Level3,
            bbbee_certificate_number: Some("BEE-2024-01234".to_string()),
            bbbee_expiry_date: Some("2025-05-31".to_string()),
            bbbee_verification_agency: Some("SANAS".to_string()),
            categories: vec![
                SupplierCategory {
                    code: "MIN-001".to_string(),
                    name: "Mining Equipment".to_string(),
                    description: "Mining machinery and equipment".to_string(),
                },
                SupplierCategory {
                    code: "MIN-002".to_string(),
                    name: "Mining Consumables".to_string(),
                    description: "Mining consumables and PPE".to_string(),
                },
            ],
            performance_score: PerformanceScore {
                overall: 81.0,
                quality: 83.0,
                delivery: 79.0,
                price: 82.0,
                responsiveness: 78.0,
                compliance: 83.0,
            },
            performance_history: vec![
                PerformanceTrend { period: "2024-Q1".to_string(), score: 79.0 },
                PerformanceTrend { period: "2024-Q2".to_string(), score: 80.0 },
                PerformanceTrend { period: "2024-Q3".to_string(), score: 80.5 },
                PerformanceTrend { period: "2024-Q4".to_string(), score: 81.0 },
            ],
            risk_rating: RiskRating::Medium,
            risk_indicators: vec![
                RiskIndicator {
                    id: "RISK-008".to_string(),
                    category: "Compliance".to_string(),
                    indicator: "Certificate expiring within 90 days".to_string(),
                    severity: RiskRating::Low,
                    description: "B-BBEE certificate requires renewal within 90 days".to_string(),
                    detected_at: "2025-02-01".to_string(),
                    status: RiskIndicatorStatus::Open,
                },
            ],
            risk_score: 35.0,
            contact_person: "Willem Botha".to_string(),
            email: "willem@nwmining.co.za".to_string(),
            phone: "+27 18 678 9012".to_string(),
            physical_address: "789 Mining Road, Rustenburg, 0299".to_string(),
            postal_address: None,
            province: "North West".to_string(),
            city: "Rustenburg".to_string(),
            bank_name: Some("First National Bank".to_string()),
            bank_account_number: Some("****5678".to_string()),
            bank_branch_code: Some("250655".to_string()),
            status: SupplierStatus::Active,
            registered_at: "2016-11-08".to_string(),
            verified_at: Some("2016-11-15".to_string()),
            last_active: "2025-02-03".to_string(),
            active_contracts: 2,
            total_contract_value: 22_000_000.0,
            contracts: vec![],
            csd_number: Some("MAAA0034568".to_string()),
            csd_verified: true,
        },
    ];

    store.suppliers.set(mock_suppliers.clone());

    // Calculate KPIs
    let total = mock_suppliers.len() as u32;
    let active = mock_suppliers.iter().filter(|s| s.status == SupplierStatus::Active).count() as u32;
    let pending = mock_suppliers.iter().filter(|s| s.status == SupplierStatus::Pending).count() as u32;
    let bbbee_compliant = mock_suppliers.iter()
        .filter(|s| s.bbbee_level != BbbeeLevel::NonCompliant)
        .count() as f64;
    let bbbee_percent = (bbbee_compliant / total as f64) * 100.0;
    let avg_perf: f64 = mock_suppliers.iter().map(|s| s.performance_score.overall).sum::<f64>() / total as f64;
    let high_risk = mock_suppliers.iter()
        .filter(|s| s.risk_rating == RiskRating::High || s.risk_rating == RiskRating::Critical)
        .count() as u32;

    store.kpis.set(SupplierKpis {
        total_suppliers: total,
        active_suppliers: active,
        pending_verification: pending,
        bbbee_compliant_percent: bbbee_percent,
        avg_performance_score: avg_perf,
        high_risk_count: high_risk,
        expiring_certificates: 3,
    });

    store.pagination.set(PaginationState {
        current_page: 1,
        page_size: 10,
        total_items: total,
        total_pages: ((total as f32) / 10.0).ceil() as u32,
    });
}

/// Select a supplier by ID
pub fn select_supplier(store: &SuppliersStore, supplier_id: &str) {
    let supplier = store.suppliers.get().iter()
        .find(|s| s.id == supplier_id)
        .cloned();
    store.selected.set(supplier);
}

/// Clear selected supplier
pub fn clear_selection(store: &SuppliersStore) {
    store.selected.set(None);
}

/// Apply filters to supplier list
pub fn apply_filters(store: &SuppliersStore) {
    // In production, this would trigger an API call with filter params
    // For now, the filtering is handled in the UI layer
}
