//! Tenders store

use components::prelude::*;
use super::types::{Tender, TenderFilter, TenderType, TenderStatus, PaginationState, EvaluationCriterion, TenderDocument, Bid, BidStatus};

/// Tenders state store
#[derive(Clone)]
pub struct TendersStore {
    pub tenders: Signal<Vec<Tender>>,
    pub selected: Signal<Option<Tender>>,
    pub filter: Signal<TenderFilter>,
    pub pagination: Signal<PaginationState>,
    pub loading: Signal<bool>,
    pub error: Signal<Option<String>>,
}

impl TendersStore {
    pub fn new() -> Self {
        Self {
            tenders: signal(Vec::new()),
            selected: signal(None),
            filter: signal(TenderFilter::default()),
            pagination: signal(PaginationState::default()),
            loading: signal(false),
            error: signal(None),
        }
    }
}

/// Load mock data for demo
pub fn load_mock_data(store: &TendersStore) {
    let mock_tenders = vec![
        Tender {
            id: "TND-2025-0089".to_string(),
            reference_number: "RFP-2025-0089".to_string(),
            title: "IT Infrastructure Upgrade - Data Centre Modernization".to_string(),
            description: "Comprehensive upgrade of data centre infrastructure including servers, storage, and network equipment.".to_string(),
            tender_type: TenderType::Rfp,
            status: TenderStatus::Open,
            estimated_value: 15_500_000.0,
            currency: "ZAR".to_string(),
            created_at: "2025-01-15".to_string(),
            publish_date: Some("2025-01-20".to_string()),
            closing_date: Some("2025-02-28".to_string()),
            briefing_date: Some("2025-01-25".to_string()),
            award_date: None,
            category: "Information Technology".to_string(),
            department: "Corporate Services".to_string(),
            cost_center: "CC-IT-001".to_string(),
            delivery_location: "Head Office, Johannesburg".to_string(),
            contract_duration: "36 months".to_string(),
            scope_of_work: "Supply, installation, and maintenance of data centre infrastructure.".to_string(),
            technical_requirements: "Must comply with Tier 3 data centre standards.".to_string(),
            mandatory_requirements: vec![
                "Valid B-BBEE certificate".to_string(),
                "Minimum 5 years experience".to_string(),
                "ISO 27001 certification".to_string(),
            ],
            evaluation_criteria: vec![
                EvaluationCriterion {
                    id: "EC-001".to_string(),
                    name: "Technical Capability".to_string(),
                    description: "Assessment of technical solution proposed".to_string(),
                    weight: 40.0,
                    max_score: 100,
                },
                EvaluationCriterion {
                    id: "EC-002".to_string(),
                    name: "Experience".to_string(),
                    description: "Relevant project experience".to_string(),
                    weight: 30.0,
                    max_score: 100,
                },
                EvaluationCriterion {
                    id: "EC-003".to_string(),
                    name: "Resources".to_string(),
                    description: "Available skills and resources".to_string(),
                    weight: 30.0,
                    max_score: 100,
                },
            ],
            price_weight: 80.0,
            bbbee_weight: 20.0,
            functionality_threshold: 70.0,
            documents: vec![
                TenderDocument {
                    id: "DOC-001".to_string(),
                    name: "Technical Specifications.pdf".to_string(),
                    file_type: "application/pdf".to_string(),
                    size: 2_450_000,
                    uploaded_at: "2025-01-15".to_string(),
                    category: "specification".to_string(),
                },
                TenderDocument {
                    id: "DOC-002".to_string(),
                    name: "Terms and Conditions.pdf".to_string(),
                    file_type: "application/pdf".to_string(),
                    size: 850_000,
                    uploaded_at: "2025-01-15".to_string(),
                    category: "terms".to_string(),
                },
            ],
            bids: vec![
                Bid {
                    id: "BID-001".to_string(),
                    tender_id: "TND-2025-0089".to_string(),
                    supplier_id: "SUP-001".to_string(),
                    supplier_name: "TechSolutions SA (Pty) Ltd".to_string(),
                    submitted_at: "2025-02-20".to_string(),
                    total_price: 14_250_000.0,
                    bbbee_level: Some(1),
                    status: BidStatus::Compliant,
                    technical_score: Some(85.0),
                    price_score: None,
                    bbbee_score: None,
                    total_score: None,
                },
                Bid {
                    id: "BID-002".to_string(),
                    tender_id: "TND-2025-0089".to_string(),
                    supplier_id: "SUP-002".to_string(),
                    supplier_name: "DataCore Systems".to_string(),
                    submitted_at: "2025-02-22".to_string(),
                    total_price: 15_800_000.0,
                    bbbee_level: Some(2),
                    status: BidStatus::UnderReview,
                    technical_score: None,
                    price_score: None,
                    bbbee_score: None,
                    total_score: None,
                },
            ],
            portal_reference: Some("eTender-2025-0089".to_string()),
            portal_url: Some("https://etenders.gov.za/tender/2025-0089".to_string()),
            deviation_type: None,
            deviation_justification: None,
            deviation_approved_by: None,
            deviation_approved_at: None,
            created_by: "John Smith".to_string(),
            last_modified_by: "John Smith".to_string(),
            last_modified_at: "2025-01-20".to_string(),
        },
        Tender {
            id: "TND-2025-0090".to_string(),
            reference_number: "RFQ-2025-0090".to_string(),
            title: "Office Furniture Procurement".to_string(),
            description: "Supply of ergonomic office furniture for new building wing.".to_string(),
            tender_type: TenderType::Rfq,
            status: TenderStatus::Draft,
            estimated_value: 850_000.0,
            currency: "ZAR".to_string(),
            created_at: "2025-02-01".to_string(),
            publish_date: None,
            closing_date: None,
            briefing_date: None,
            award_date: None,
            category: "Furniture & Fittings".to_string(),
            department: "Facilities Management".to_string(),
            cost_center: "CC-FAC-002".to_string(),
            delivery_location: "Building B, Pretoria".to_string(),
            contract_duration: "Once-off".to_string(),
            scope_of_work: "Supply and delivery of office furniture.".to_string(),
            technical_requirements: "SABS approved furniture meeting ergonomic standards.".to_string(),
            mandatory_requirements: vec![
                "Valid B-BBEE certificate".to_string(),
                "SABS certification".to_string(),
            ],
            evaluation_criteria: vec![],
            price_weight: 90.0,
            bbbee_weight: 10.0,
            functionality_threshold: 60.0,
            documents: vec![],
            bids: vec![],
            portal_reference: None,
            portal_url: None,
            deviation_type: None,
            deviation_justification: None,
            deviation_approved_by: None,
            deviation_approved_at: None,
            created_by: "Jane Doe".to_string(),
            last_modified_by: "Jane Doe".to_string(),
            last_modified_at: "2025-02-01".to_string(),
        },
        Tender {
            id: "TND-2025-0091".to_string(),
            reference_number: "RFT-2025-0091".to_string(),
            title: "Security Services - Guarding and Access Control".to_string(),
            description: "Provision of comprehensive security services for all facilities.".to_string(),
            tender_type: TenderType::Rft,
            status: TenderStatus::Evaluation,
            estimated_value: 24_000_000.0,
            currency: "ZAR".to_string(),
            created_at: "2024-12-01".to_string(),
            publish_date: Some("2024-12-10".to_string()),
            closing_date: Some("2025-01-31".to_string()),
            briefing_date: Some("2024-12-15".to_string()),
            award_date: None,
            category: "Security Services".to_string(),
            department: "Corporate Services".to_string(),
            cost_center: "CC-SEC-001".to_string(),
            delivery_location: "All Facilities".to_string(),
            contract_duration: "60 months".to_string(),
            scope_of_work: "24/7 guarding services, access control, and monitoring.".to_string(),
            technical_requirements: "PSIRA registered guards, armed response capability.".to_string(),
            mandatory_requirements: vec![
                "Valid B-BBEE certificate".to_string(),
                "PSIRA registration".to_string(),
                "Minimum 10 years experience".to_string(),
                "Armed response capability".to_string(),
            ],
            evaluation_criteria: vec![
                EvaluationCriterion {
                    id: "EC-001".to_string(),
                    name: "Methodology".to_string(),
                    description: "Proposed approach and methodology".to_string(),
                    weight: 35.0,
                    max_score: 100,
                },
                EvaluationCriterion {
                    id: "EC-002".to_string(),
                    name: "Experience".to_string(),
                    description: "Track record in similar contracts".to_string(),
                    weight: 35.0,
                    max_score: 100,
                },
                EvaluationCriterion {
                    id: "EC-003".to_string(),
                    name: "Resources".to_string(),
                    description: "Personnel and equipment".to_string(),
                    weight: 30.0,
                    max_score: 100,
                },
            ],
            price_weight: 80.0,
            bbbee_weight: 20.0,
            functionality_threshold: 75.0,
            documents: vec![
                TenderDocument {
                    id: "DOC-003".to_string(),
                    name: "Security Specifications.pdf".to_string(),
                    file_type: "application/pdf".to_string(),
                    size: 1_200_000,
                    uploaded_at: "2024-12-01".to_string(),
                    category: "specification".to_string(),
                },
            ],
            bids: vec![
                Bid {
                    id: "BID-003".to_string(),
                    tender_id: "TND-2025-0091".to_string(),
                    supplier_id: "SUP-003".to_string(),
                    supplier_name: "SecureGuard Holdings".to_string(),
                    submitted_at: "2025-01-30".to_string(),
                    total_price: 22_500_000.0,
                    bbbee_level: Some(1),
                    status: BidStatus::Shortlisted,
                    technical_score: Some(88.0),
                    price_score: Some(92.0),
                    bbbee_score: Some(100.0),
                    total_score: Some(91.2),
                },
                Bid {
                    id: "BID-004".to_string(),
                    tender_id: "TND-2025-0091".to_string(),
                    supplier_id: "SUP-004".to_string(),
                    supplier_name: "Protea Security Services".to_string(),
                    submitted_at: "2025-01-29".to_string(),
                    total_price: 23_800_000.0,
                    bbbee_level: Some(2),
                    status: BidStatus::Shortlisted,
                    technical_score: Some(92.0),
                    price_score: Some(85.0),
                    bbbee_score: Some(90.0),
                    total_score: Some(87.5),
                },
            ],
            portal_reference: Some("eTender-2024-0091".to_string()),
            portal_url: Some("https://etenders.gov.za/tender/2024-0091".to_string()),
            deviation_type: None,
            deviation_justification: None,
            deviation_approved_by: None,
            deviation_approved_at: None,
            created_by: "Peter Jones".to_string(),
            last_modified_by: "Peter Jones".to_string(),
            last_modified_at: "2025-02-05".to_string(),
        },
        Tender {
            id: "TND-2025-0092".to_string(),
            reference_number: "RFP-2025-0092".to_string(),
            title: "Professional Services - Internal Audit".to_string(),
            description: "Outsourced internal audit services for 3-year period.".to_string(),
            tender_type: TenderType::Rfp,
            status: TenderStatus::PendingApproval,
            estimated_value: 4_500_000.0,
            currency: "ZAR".to_string(),
            created_at: "2025-02-10".to_string(),
            publish_date: None,
            closing_date: None,
            briefing_date: None,
            award_date: None,
            category: "Professional Services".to_string(),
            department: "Finance".to_string(),
            cost_center: "CC-FIN-001".to_string(),
            delivery_location: "Head Office".to_string(),
            contract_duration: "36 months".to_string(),
            scope_of_work: "Internal audit services as per approved audit plan.".to_string(),
            technical_requirements: "Registered auditors with public sector experience.".to_string(),
            mandatory_requirements: vec![
                "Valid B-BBEE certificate".to_string(),
                "IRBA registration".to_string(),
                "Professional indemnity insurance".to_string(),
            ],
            evaluation_criteria: vec![
                EvaluationCriterion {
                    id: "EC-001".to_string(),
                    name: "Audit Approach".to_string(),
                    description: "Proposed audit methodology".to_string(),
                    weight: 40.0,
                    max_score: 100,
                },
                EvaluationCriterion {
                    id: "EC-002".to_string(),
                    name: "Team Qualifications".to_string(),
                    description: "Qualifications and experience of audit team".to_string(),
                    weight: 40.0,
                    max_score: 100,
                },
                EvaluationCriterion {
                    id: "EC-003".to_string(),
                    name: "References".to_string(),
                    description: "Relevant public sector references".to_string(),
                    weight: 20.0,
                    max_score: 100,
                },
            ],
            price_weight: 80.0,
            bbbee_weight: 20.0,
            functionality_threshold: 70.0,
            documents: vec![],
            bids: vec![],
            portal_reference: None,
            portal_url: None,
            deviation_type: None,
            deviation_justification: None,
            deviation_approved_by: None,
            deviation_approved_at: None,
            created_by: "Sarah Williams".to_string(),
            last_modified_by: "Sarah Williams".to_string(),
            last_modified_at: "2025-02-10".to_string(),
        },
        Tender {
            id: "TND-2025-0093".to_string(),
            reference_number: "RFQ-2025-0093".to_string(),
            title: "Vehicle Fleet Maintenance".to_string(),
            description: "Maintenance services for corporate vehicle fleet.".to_string(),
            tender_type: TenderType::Rfq,
            status: TenderStatus::Awarded,
            estimated_value: 1_200_000.0,
            currency: "ZAR".to_string(),
            created_at: "2024-11-01".to_string(),
            publish_date: Some("2024-11-05".to_string()),
            closing_date: Some("2024-11-30".to_string()),
            briefing_date: None,
            award_date: Some("2024-12-15".to_string()),
            category: "Fleet Services".to_string(),
            department: "Operations".to_string(),
            cost_center: "CC-OPS-003".to_string(),
            delivery_location: "Multiple Locations".to_string(),
            contract_duration: "24 months".to_string(),
            scope_of_work: "Scheduled and ad-hoc vehicle maintenance.".to_string(),
            technical_requirements: "Authorized service centres for fleet brands.".to_string(),
            mandatory_requirements: vec![
                "Valid B-BBEE certificate".to_string(),
                "Authorized dealer status".to_string(),
            ],
            evaluation_criteria: vec![],
            price_weight: 90.0,
            bbbee_weight: 10.0,
            functionality_threshold: 60.0,
            documents: vec![],
            bids: vec![
                Bid {
                    id: "BID-005".to_string(),
                    tender_id: "TND-2025-0093".to_string(),
                    supplier_id: "SUP-005".to_string(),
                    supplier_name: "AutoCare Services".to_string(),
                    submitted_at: "2024-11-28".to_string(),
                    total_price: 1_150_000.0,
                    bbbee_level: Some(2),
                    status: BidStatus::Awarded,
                    technical_score: Some(78.0),
                    price_score: Some(95.0),
                    bbbee_score: Some(90.0),
                    total_score: Some(92.0),
                },
            ],
            portal_reference: Some("eTender-2024-0093".to_string()),
            portal_url: Some("https://etenders.gov.za/tender/2024-0093".to_string()),
            deviation_type: None,
            deviation_justification: None,
            deviation_approved_by: None,
            deviation_approved_at: None,
            created_by: "Mike Brown".to_string(),
            last_modified_by: "Mike Brown".to_string(),
            last_modified_at: "2024-12-15".to_string(),
        },
    ];

    store.tenders.set(mock_tenders);
    store.pagination.set(PaginationState {
        current_page: 1,
        page_size: 10,
        total_items: 5,
        total_pages: 1,
    });
}

/// Apply filters to tender list
pub fn apply_filters(store: &TendersStore) {
    // In production, this would trigger an API call with filter params
    // For now, the filtering is handled in the UI layer
}

/// Set selected tender
pub fn select_tender(store: &TendersStore, tender_id: &str) {
    let tender = store.tenders.get().iter()
        .find(|t| t.id == tender_id)
        .cloned();
    store.selected.set(tender);
}

/// Clear selected tender
pub fn clear_selection(store: &TendersStore) {
    store.selected.set(None);
}
